## Paraphrases Template

In [36]:
from google.colab import drive
drive.mount('/content/drive')
BASE_PATH = '/content/drive/My Drive/MAI/Quinto Semestre/IHLT/assets/'

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [37]:
import pandas as pd

In [38]:
dt = pd.read_csv(f'{BASE_PATH}test-gold/STS.input.SMTeuroparl.txt',sep='\t',header=None)

In [39]:
dt.head(10)

,0,1
0,The leaders have now been given a new chance a...,The leaders benefit aujourd' hui of a new luck...
1,Amendment No 7 proposes certain changes in the...,Amendment No 7 is proposing certain changes in...
2,Let me remind you that our allies include ferv...,I would like to remind you that among our alli...
3,The vote will take place today at 5.30 p.m.,The vote will take place at 5.30pm
4,"The fishermen are inactive, tired and disappoi...","The fishermen are inactive, tired and disappoi..."

In [40]:
dt['gs'] = pd.read_csv(f'{BASE_PATH}test-gold/STS.gs.SMTeuroparl.txt',sep='\t',header=None)

In [41]:
dt.shape

(459, 3)

In [42]:
dt.head()

,0,1,gs
0,The leaders have now been given a new chance a...,The leaders benefit aujourd' hui of a new luck...,4.50
1,Amendment No 7 proposes certain changes in the...,Amendment No 7 is proposing certain changes in...,5.00
2,Let me remind you that our allies include ferv...,I would like to remind you that among our alli...,4.25
3,The vote will take place today at 5.30 p.m.,The vote will take place at 5.30pm,4.50
4,"The fishermen are inactive, tired and disappoi...","The fishermen are inactive, tired and disappoi...",5.00

## TODO
1. Compute the Jaccard similarity between every paraphrase and add a column *jaccard* to *dt* variable.
2. Compute the pearson correlation as: <br>
```
from scipy.stats import pearsonr
pearsonr(dt['gs'], dt['jaccard'])[0]
```

## NLTK Tokenizer

In [43]:
import nltk
nltk.download('punkt_tab')

dt_tokens = dt.loc[:, [0, 1]].applymap(nltk.word_tokenize)
dt_tokens.head(10)

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
/tmp/ipykernel_516/4160789469.py:4: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  dt_tokens = dt.loc[:, [0, 1]].applymap(nltk.word_tokenize)

,0,1
0,"[The, leaders, have, now, been, given, a, new,...","[The, leaders, benefit, aujourd, ', hui, of, a..."
1,"[Amendment, No, 7, proposes, certain, changes,...","[Amendment, No, 7, is, proposing, certain, cha..."
2,"[Let, me, remind, you, that, our, allies, incl...","[I, would, like, to, remind, you, that, among,..."
3,"[The, vote, will, take, place, today, at, 5.30...","[The, vote, will, take, place, at, 5.30pm]"
4,"[The, fishermen, are, inactive, ,, tired, and,...","[The, fishermen, are, inactive, ,, tired, and,..."

## Compute the Jaccard similarity

In [44]:
from nltk.metrics.distance import jaccard_distance
dt['jaccard'] = dt_tokens.apply(lambda row: jaccard_distance(set(str(row[0]).split()), set(str(row[1]).split())), axis=1)
dt.head(10)

,0,1,gs,jaccard
0,The leaders have now been given a new chance a...,The leaders benefit aujourd' hui of a new luck...,4.50,0.653846
1,Amendment No 7 proposes certain changes in the...,Amendment No 7 is proposing certain changes in...,5.00,0.214286
2,Let me remind you that our allies include ferv...,I would like to remind you that among our alli...,4.25,0.608696
3,The vote will take place today at 5.30 p.m.,The vote will take place at 5.30pm,4.50,0.454545
4,"The fishermen are inactive, tired and disappoi...","The fishermen are inactive, tired and disappoi...",5.00,0.000000

## Compute the pearson correlation

In [45]:
from scipy.stats import pearsonr
pearsonr(dt['gs'], dt['jaccard'])[0]

np.float64(-0.4505143566550619)